
      INFO   Will watch for changes in these directories: ['/Users/N133723/Desktop/tlabchaat-355-24/cost-estimator-calc-service']
      INFO   Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
      INFO   Started reloader process [42510] using WatchFiles
2025-08-01 01:43:46,975 | INFO | cost_estimator_calc_service | Async SpannerClient initialized for database: projects/anbc-hcb-dev/instances/provider-de/databases/cost-estimator-secure
2025-08-01 01:43:46,975 | INFO | cost_estimator_calc_service | Connection pool size: 10, Max workers: 20
2025-08-01 01:43:46,975 | INFO | cost_estimator_calc_service | Executing async query: SELECT payment_method_cd, score FROM payment_method_hierarchy
2025-08-01 01:43:46,975 | INFO | cost_estimator_calc_service | Query params: None
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/N133723/Desktop/tlabchaat-355-24/cost-estimator-calc-service/app/repository/impl/cost_estimator_repository_impl.py", line 30, in __init__
    asyncio.get_event_loop().run_until_complete(self.load_payment_method_hierarchy())
  File "uvloop/loop.pyx", line 1512, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1505, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1379, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 520, in uvloop.loop.Loop._run
RuntimeError: this event loop is already running.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/N133723/Library/Python/3.12/lib/python/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/N133723/Library/Python/3.12/lib/python/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/Users/N133723/Library/Python/3.12/lib/python/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/Users/N133723/Library/Python/3.12/lib/python/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/Users/N133723/Library/Python/3.12/lib/python/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/N133723/Library/Python/3.12/lib/python/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/N133723/Desktop/tlabchaat-355-24/cost-estimator-calc-service/app/main.py", line 21, in <module>
    repository = CostEstimatorRepositoryImpl()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/N133723/Desktop/tlabchaat-355-24/cost-estimator-calc-service/app/repository/impl/cost_estimator_repository_impl.py", line 34, in __init__
    loop.run_until_complete(self.load_payment_method_hierarchy())
  File "uvloop/loop.pyx", line 1512, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1505, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1379, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 524, in uvloop.loop.Loop._run
RuntimeError: Cannot run the event loop while another loop is running
sys:1: RuntimeWarning: coroutine 'CostEstimatorRepositoryImpl.load_payment_method_hierarchy' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
