Application startup complete.
2025-07-31 00:24:50,682 | INFO | cost_estimator_calc_service | Async SpannerClient initialized for database: projects/anbc-hcb-dev/instances/provider-de/databases/cost-estimator-secure
2025-07-31 00:24:50,682 | INFO | cost_estimator_calc_service | Connection pool size: 10, Max workers: 20
benefit_request benefitProductType='Medical' membershipID='5~265642286+34+44+20250101+784461+AM+39' planIdentifier='3~' serviceInfo=[ServiceInfo(serviceCodeInfo=ServiceCodeInfo(providerType=[ProviderType(code='IO')], placeOfService=[PlaceOfService(code='21')], providerSpecialty=[ProviderSpecialty(code=' ')], code='28054', type='CPT4'))]
CostEstimatorRateCriteria fields: {'providerIdentificationNumber': <class 'str'>, 'serviceCode': <class 'str'>, 'serviceType': <class 'str'>, 'serviceLocationNumber': typing.Optional[str], 'networkId': typing.Optional[str], 'placeOfService': <class 'str'>, 'zipCode': <class 'str'>, 'isOutofNetwork': <class 'bool'>, 'providerSpecialtyCode': typing.Optional[str], 'providerType': typing.Optional[str]}
rate_criteria CostEstimatorRateCriteria(providerIdentificationNumber='9394609', serviceCode='28054', serviceType='CPT4', serviceLocationNumber='10701', networkId='12395', placeOfService='21', zipCode='07083', isOutofNetwork=False, providerSpecialtyCode=' ', providerType='IO')
2025-07-31 00:24:50,685 | INFO | cost_estimator_calc_service | Executing async query: SELECT MAX(RATE) AS RATE
FROM CET_CLAIM_BASED_AMOUNTS
WHERE
    PROVIDER_IDENTIFICATION_NBR = @provideridentificationnumber
    AND NETWORK_ID = @networkid
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
2025-07-31 00:24:50,685 | INFO | cost_estimator_calc_service | Query params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
2025-07-31 00:24:53,095 | INFO | cost_estimator_calc_service | Successfully retrieved new token
2025-07-31 00:24:53,130 | INFO | cost_estimator_calc_service | Successfully retrieved new token
2025-07-31 00:24:54,067 | INFO | cost_estimator_calc_service | Claim-based rate result: [[None]]
2025-07-31 00:24:54,067 | WARNING | cost_estimator_calc_service | Empty or malformed result
2025-07-31 00:24:54,067 | INFO | cost_estimator_calc_service | No claim-based rate found, proceeding to get provider info
2025-07-31 00:24:54,067 | INFO | cost_estimator_calc_service | Executing async query: 
                    SELECT DISTINCT PRODUCT_CD, PROVIDER_BUSINESS_GROUP_NBR
                    FROM CET_RATES
                    WHERE SERVICE_CD = @servicecd
                      AND SERVICE_TYPE_CD = @servicetype
                      AND PLACE_OF_SERVICE_CD = @placeofservice
                      AND PROVIDER_BUSINESS_GROUP_NBR = @providerbusinessgroupnbr
                
2025-07-31 00:24:54,067 | INFO | cost_estimator_calc_service | Query params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1753939494.070998 2503990 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
2025-07-31 00:24:56,363 | ERROR | cost_estimator_calc_service | Error executing async read-only query: 400 No parameter found for binding: providerbusinessgroupnbr
2025-07-31 00:24:56,364 | ERROR | cost_estimator_calc_service | Query: 
                    SELECT DISTINCT PRODUCT_CD, PROVIDER_BUSINESS_GROUP_NBR
                    FROM CET_RATES
                    WHERE SERVICE_CD = @servicecd
                      AND SERVICE_TYPE_CD = @servicetype
                      AND PLACE_OF_SERVICE_CD = @placeofservice
                      AND PROVIDER_BUSINESS_GROUP_NBR = @providerbusinessgroupnbr
                
2025-07-31 00:24:56,364 | ERROR | cost_estimator_calc_service | Params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
2025-07-31 00:24:56,364 | ERROR | cost_estimator_calc_service | Exception type: <class 'google.api_core.exceptions.InvalidArgument'>
2025-07-31 00:24:56,364 | ERROR | cost_estimator_calc_service | Exception details: 400 No parameter found for binding: providerbusinessgroupnbr
2025-07-31 00:24:56,365 | INFO | cost_estimator_calc_service | Extraction result from CET_RATES: []
2025-07-31 00:24:56,365 | WARNING | cost_estimator_calc_service | Could not get provider info from CET_RATES, falling back to _get_provider_info: CET_RATES did not return any product/provider info
2025-07-31 00:24:56,366 | INFO | cost_estimator_calc_service | Executing async query: SELECT DISTINCT PROVIDER_BUSINESS_GROUP_NBR, PRODUCT_CD, RATING_SYSTEM_CD, EPDB_GEOGRAPHIC_AREA_CD
FROM CET_PROVIDERS
WHERE
    PROVIDER_IDENTIFICATION_NBR = @provideridentificationnumber
    AND NETWORK_ID = @networkid
    AND SERVICE_LOCATION_NBR = @servicelocationnumber
2025-07-31 00:24:56,366 | INFO | cost_estimator_calc_service | Query params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
I0000 00:00:1753939496.371498 2503990 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
2025-07-31 00:24:58,973 | INFO | cost_estimator_calc_service | Provider info result: [['100004781', 'MC', 'REF', 'GN02']]
2025-07-31 00:24:58,973 | INFO | cost_estimator_calc_service | Executing default rate query: SELECT payment_method_cd, RATE
FROM CET_RATES
WHERE
    SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND PRODUCT_CD = @productcd
    AND PROVIDER_BUSINESS_GROUP_NBR IN UNNEST(@providerbusinessgroupnbr)
    AND CONTRACT_TYPE = 'D' with params: {'servicecd': '28054', 'placeofservice': '21', 'servicetype': 'CPT4', 'productcd': 'MC', 'ratesystemcd': 'REF', 'geographicareacd': 'GN02', 'providerbusinessgroupnbr': ['100004781']}
2025-07-31 00:24:58,974 | INFO | cost_estimator_calc_service | Executing async query: SELECT payment_method_cd, RATE
FROM CET_RATES
WHERE
    SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND PRODUCT_CD = @productcd
    AND PROVIDER_BUSINESS_GROUP_NBR IN UNNEST(@providerbusinessgroupnbr)
    AND CONTRACT_TYPE = 'D'
2025-07-31 00:24:58,974 | INFO | cost_estimator_calc_service | Query params: {'servicecd': '28054', 'placeofservice': '21', 'servicetype': 'CPT4', 'productcd': 'MC', 'ratesystemcd': 'REF', 'geographicareacd': 'GN02', 'providerbusinessgroupnbr': ['100004781']}
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
I0000 00:00:1753939500.152513 2503990 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
E0000 00:00:1753939500.216049 2504543 ssl_transport_security_utils.cc:114] Corruption detected.
E0000 00:00:1753939500.216101 2504543 ssl_transport_security_utils.cc:71] error:100003fc:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_RECORD_MAC
E0000 00:00:1753939500.216108 2504543 secure_endpoint.cc:234] Decryption error: TSI_DATA_CORRUPTED
2025-07-31 00:25:02,448 | INFO | cost_estimator_calc_service | return rows: []
2025-07-31 00:25:02,448 | INFO | cost_estimator_calc_service | No rate rows found for default payment methods
2025-07-31 00:25:02,448 | INFO | cost_estimator_calc_service | Executing async query: SELECT payment_method_cd, RATE
FROM CET_RATES
WHERE
    SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND PRODUCT_CD = @productcd
    AND PROVIDER_BUSINESS_GROUP_NBR IN UNNEST(@providerbusinessgroupnbr)
    AND CONTRACT_TYPE IN ('C', 'N')
2025-07-31 00:25:02,449 | INFO | cost_estimator_calc_service | Query params: {'servicecd': '28054', 'placeofservice': '21', 'servicetype': 'CPT4', 'productcd': 'MC', 'ratesystemcd': 'REF', 'geographicareacd': 'GN02', 'providerbusinessgroupnbr': ['100004781']}
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
I0000 00:00:1753939502.453262 2503990 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
E0000 00:00:1753939502.514029 2504543 ssl_transport_security_utils.cc:114] Corruption detected.
E0000 00:00:1753939502.514076 2504543 ssl_transport_security_utils.cc:71] error:100003fc:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_RECORD_MAC
E0000 00:00:1753939502.514081 2504543 secure_endpoint.cc:234] Decryption error: TSI_DATA_CORRUPTED
2025-07-31 00:25:04,743 | INFO | cost_estimator_calc_service | No rate rows found for non-standard payment methods
      INFO   127.0.0.1:59250 - "POST /costestimator/v1/rate HTTP/1.1" 200
